--린트 문법 체크 사이트 http://www.yamllint.com/
--DB 연결 https://jojoldu.tistory.com/325
---
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  profiles:
    active: real

spring.batch.job.names: ${job.name:NONE}
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
spring:
  profiles: real
  datasource:
    hikari:
      jdbc-url: ENC(kCI87baayXzDmzEyk9Y/67F46cgFqok1DzaoNULeZ8EvC/adfvoFukiRWU5e1FDQFELNq4NuZ94T+ERTmpGEtk0Q04ITNYf7MK9QM84pzhdZGPaY5Samw9qOL2eU0Tdjr7sjc9Lv2aoNWDu2+p1U+A/B6T7frPpUu45+2WFM10/+U3UoJ9jiH/7ItdzJwnC0rbg0DvuJP5/tJQcIbSS+pg==)
      username: ENC(tJaNGcK+tTmCmppOWdAOQwZynaCO8jdOKW5D9ZBH1PA=)
      password: ENC(vg1XlJIZbUuCC3mYLcFTaOLXxAXtIVWnaMOsfS6pck4=)
      driver-class-name: com.mysql.cj.jdbc.Driver
      logging:
        level: debug

