--린트 문법 체크 사이트 http://www.yamllint.com/
--DB 연결 https://jojoldu.tistory.com/325
---
spring:
  profiles:
    active: local

spring.batch.job.names: ${job.name:NONE}
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
spring:
  profiles: real
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batch_db
      username: ym
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      logging:
        level: debug
