--린트 문법 체크 사이트 http://www.yamllint.com/
--DB 연결 https://jojoldu.tistory.com/325
---
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  profiles:
    active: real
  pid:
    file: boot.pid

spring.batch.job.names: ${job.name:NONE}
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
spring:
  profiles: real
  datasource:
    hikari:
      jdbc-url: ENC(wX2W1EeJ1t4MdYYiqROeA+ekN2hAj6SKesumbVx0hoRJ4tlKlz/Zv4xoL0KHYgi794hCbfLnjxc18/Kyg5OyV55fMASUmY96qkEbMLYgzlInHfFBrT9HAW8xLOazy5lMqDcCufo0dgXn0EdVfsHmNCIbQrFR5QHGM3d8uh8FA2ALlbUw2hV8N30KZ0atFGfwebfs1k63ncHYCajJB9aA2w==)
      username: ENC(bsYmN3qYRLXEx+c845WRV/eIWxfr2fWeaqyCkvg99W0=)
      password: ENC(etdqkaXWoqB29Q4hoZS5gbQhyJCfoytj2HCG+29UTug=)
      driver-class-name: com.mysql.cj.jdbc.Driver
      logging:
        level: debug

